owners:
  # your telegram username here
  #  You can save it if you need it, but I don't use this anywhere
  - "@UnearthlyCatS"

support_users:
  #also your username, owners not use in the support team
  - "@UnearthlyCatS"

